"""
extract_municipales_datagouv.py

Extract Paris municipal election results from the data.gouv.fr aggregated
candidate-level parquet file and save them as individual long-format parquet
files matching the existing municipal cleaner schema.

Input:
- data/raw_datagouv/datagouv_candidats_results.parquet

Output:
- data/raw/elections-municipales-YEAR-Xtour.parquet

The output is long-format:
one row = one polling station x one candidate/list.

Required by clean_municipal_results.py:
- scrutin
- annee
- tour
- candidate
- votes
- source_bv_id

The input parquet is generated by:

    python src/get_data/download/download_datagouv_candidats_results.py

Run from project root:

    python src/get_data/download/extract_municipales_datagouv.py
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

# ── Paths ────────────────────────────────────────────────────────────────────

PROJECT_ROOT = Path(__file__).resolve().parents[3]

INPUT_PATH = PROJECT_ROOT / "data" / "raw_datagouv" / "datagouv_candidats_results.parquet"
OUTPUT_DIR = PROJECT_ROOT / "data" / "raw"


# ── Config ───────────────────────────────────────────────────────────────────

MUNICIPAL_ELECTIONS = [
    "2008_muni_t1",
    "2008_muni_t2",
    "2014_muni_t1",
    "2014_muni_t2",
    "2020_muni_t1",
    "2020_muni_t2",
]

TOUR_LABEL = {
    "t1": "1ertour",
    "t2": "2emetour",
}


# ── Helpers ──────────────────────────────────────────────────────────────────

def require_input_file() -> None:
    """Fail early with a helpful reproducibility error if input is missing."""
    if INPUT_PATH.exists():
        return

    raise FileNotFoundError(
        "\nMissing required data.gouv.fr candidate results parquet:\n"
        f"  {INPUT_PATH}\n\n"
        "This file is generated locally and is intentionally not committed to Git.\n"
        "Run this first from the project root:\n\n"
        "  python src/get_data/download/download_datagouv_candidats_results.py\n\n"
        "Then rerun:\n\n"
        "  python src/get_data/download/extract_municipales_datagouv.py\n"
    )


def parse_id_election(id_election: str) -> dict:
    """Parse '2020_muni_t1' into year, election type, and round."""
    parts = str(id_election).split("_")

    if len(parts) != 3:
        raise ValueError(f"Unexpected municipal id_election format: {id_election}")

    return {
        "annee": int(parts[0]),
        "scrutin": "Municipales",
        "tour": int(parts[2].replace("t", "")),
    }


def normalize_code_bv(value) -> str:
    """Return a four-digit Paris polling booth code."""
    if pd.isna(value):
        return ""

    text = str(value).strip()

    if text.endswith(".0") and text[:-2].isdigit():
        text = text[:-2]

    return text.zfill(4)


def build_source_bv_id(row: pd.Series) -> str:
    """
    Build the source_bv_id expected by clean_municipal_results.py.

    Format:
    - code_commune + "_" + code_bv
    - example: 75056_0101
    """
    code_commune = str(row.get("code_commune", "") or "").strip()
    code_bv = normalize_code_bv(row.get("code_bv"))

    return f"{code_commune}_{code_bv}"


def build_candidate_name(row: pd.Series) -> str:
    """
    Build a stable candidate/list label.

    Prefer list labels for municipal elections when available, then fall back to
    candidate name.
    """
    for col in ["liste", "libelle_etendu_liste", "libelle_abrege_liste", "nom_tete_liste"]:
        value = row.get(col)
        if pd.notna(value) and str(value).strip():
            return str(value).strip()

    nom = str(row.get("nom", "") or "").strip()
    prenom = str(row.get("prenom", "") or "").strip()

    if prenom and nom:
        return f"{nom} {prenom}"

    if nom:
        return nom

    return "unknown_candidate"


def add_vote_shares(df: pd.DataFrame) -> pd.DataFrame:
    """
    Convert data.gouv.fr percentage columns into 0-1 shares used downstream.
    """
    df = df.copy()

    if "ratio_voix_exprimes" in df.columns:
        df["vote_share_exprimes"] = (
            pd.to_numeric(df["ratio_voix_exprimes"], errors="coerce") / 100
        )
    else:
        df["vote_share_exprimes"] = pd.NA

    if "ratio_voix_inscrits" in df.columns:
        df["vote_share_registered"] = (
            pd.to_numeric(df["ratio_voix_inscrits"], errors="coerce") / 100
        )
    else:
        df["vote_share_registered"] = pd.NA

    return df


def prepare_long_municipal_rows(df: pd.DataFrame) -> pd.DataFrame:
    """Convert raw data.gouv.fr candidate rows to the cleaner's long schema."""
    df = df.copy().reset_index(drop=True)

    parsed = df["id_election"].astype(str).apply(parse_id_election).apply(pd.Series)
    df = pd.concat([df.reset_index(drop=True), parsed.reset_index(drop=True)], axis=1)

    df["source_bv_id"] = df.apply(build_source_bv_id, axis=1)
    df["candidate"] = df.apply(build_candidate_name, axis=1)
    df["votes"] = pd.to_numeric(df["voix"], errors="coerce").fillna(0)

    df = add_vote_shares(df)

    # Keep useful original candidate/list metadata when available.
    keep_columns = [
        "scrutin",
        "annee",
        "tour",
        "candidate",
        "votes",
        "source_bv_id",
        "vote_share_exprimes",
        "vote_share_registered",
        "nom",
        "prenom",
        "nuance",
        "liste",
        "libelle_abrege_liste",
        "libelle_etendu_liste",
        "nom_tete_liste",
        "id_election",
        "code_departement",
        "code_commune",
        "code_bv",
    ]

    existing_columns = [col for col in keep_columns if col in df.columns]
    out = df[existing_columns].copy()

    out = out[out["source_bv_id"].astype(str).str.match(r"^\d{5}_\d{4}$", na=False)]
    out = out[out["candidate"].astype(str).str.strip() != ""]
    out = out[pd.to_numeric(out["votes"], errors="coerce").notna()]

    return out


# ── Main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    require_input_file()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Loading {INPUT_PATH.relative_to(PROJECT_ROOT)} ...")
    df = pd.read_parquet(INPUT_PATH)

    paris_munic = df[
        (df["code_departement"].astype(str) == "75")
        & (df["id_election"].astype(str).isin(MUNICIPAL_ELECTIONS))
    ].copy()

    paris_munic = paris_munic.reset_index(drop=True)

    print(f"  Paris municipal candidate rows found: {len(paris_munic):,}")

    if paris_munic.empty:
        raise RuntimeError(
            "No Paris municipal rows found in the data.gouv.fr candidate parquet. "
            f"Expected id_election values: {MUNICIPAL_ELECTIONS}"
        )

    long_df = prepare_long_municipal_rows(paris_munic)

    print()
    print("Rows by municipal election before saving:")
    print(long_df["id_election"].value_counts(dropna=False).sort_index().to_string())
    print()

    saved_files = 0

    for id_election in MUNICIPAL_ELECTIONS:
        subset = long_df[long_df["id_election"].astype(str) == id_election].copy()

        if subset.empty:
            print(f"  WARNING: no rows for {id_election}, skipping.")
            continue

        year, _, tour_code = id_election.split("_")
        tour_label = TOUR_LABEL[tour_code]

        fname = f"elections-municipales-{year}-{tour_label}.parquet"
        out_path = OUTPUT_DIR / fname

        subset = subset.drop(columns=["id_election"], errors="ignore")
        subset.to_parquet(out_path, index=False)

        saved_files += 1

        print(f"  Saved {fname} ({len(subset):,} candidate/list rows)")

    if saved_files != len(MUNICIPAL_ELECTIONS):
        raise RuntimeError(
            f"Created {saved_files} of {len(MUNICIPAL_ELECTIONS)} required municipal files."
        )

    print()
    print("[ok] Municipal extraction complete.")
    print("Municipal raw files are long-format and ready for clean_municipal_results.py.")


if __name__ == "__main__":
    main()
